hello-world homework
amosipenko/golang-one pull request #1
Opened 2021-11-18 13:00 UTC by amosipenko

Added main.go and README.md

2021-11-18 14:04 UTC, v-lozhkin requested changes

2021-11-18 14:04 UTC, v-lozhkin commented on homework1/main.go
> +func main(){
Все отлично! Только нужно еще `go fmt homework1/main.go` запустить :)

2021-11-18 16:54 UTC, amosipenko commented on homework1/main.go
> +func main(){
fixed

2021-11-19 06:53 UTC, v-lozhkin approved these changes
Отлично, можно мержить!

2021-11-21 20:04 UTC, merged