2d homework with 4 tasks
amosipenko/golang-one pull request #2
Opened 2021-11-22 16:28 UTC by amosipenko

2021-11-23 07:30 UTC, v-lozhkin requested changes

2021-11-23 07:30 UTC, v-lozhkin commented on homework2/task1/main.go
> +		} else {
Небольшой совет по упрощению кода. Если тут убрать else  (но оставить то, что в нем) - то программа будет работать ровно так же, но код будет проще :)

2021-11-23 07:30 UTC, v-lozhkin commented on homework2/task2/main.go
> +		} else {
тут тоже можно от else избавиться

2021-11-23 07:30 UTC, v-lozhkin commented on homework2/task2/main.go
> +	var d, l float64
Это можно не править, но просто совет на будущее - переменные лучше объявлять как можно ближе к месту их использования. Так, при прочтении, будет понятнее, зачем они нужны. В данном случае я бы перенес объявление d и l к месту их вычисления

2021-11-23 07:30 UTC, v-lozhkin commented on homework2/task2/main.go
> +
Не совсем очевидно зачем пустая строка в каждом файле после func main(){

2021-11-23 07:30 UTC, v-lozhkin commented on homework2/task4/main.go
> +						if digit > nSqrt { // оптимизация этого алгоритма: можно проверять делители до корня из N
лайк за оптимизашку!

2021-11-24 18:35 UTC, amosipenko commented on homework2/task2/main.go
> +
fixed

2021-11-24 18:36 UTC, amosipenko commented on homework2/task2/main.go
> +	var d, l float64
fixed

2021-11-24 18:36 UTC, amosipenko commented on homework2/task2/main.go
> +		} else {
fixed

2021-11-24 18:36 UTC, amosipenko commented on homework2/task1/main.go
> +		} else {
fixed

2021-11-24 19:53 UTC, v-lozhkin approved these changes
Все хорошо, можно мержить

2021-11-25 20:54 UTC, v-lozhkin requested changes

2021-11-25 20:54 UTC, v-lozhkin commented on homework3/main.go
> +		if str[i] >= 48 && str[i] <= 57 || str[i] == 46 {
Идея сравнения по байтам хороша, но абсолютно нечитаема, если использовать цифры. 
Я не смогу понять, что здесь написано, пока не загляну в таблицу utf-8 (ну или верить комментам на слово). 
Так что лучше указывать конкретные символы через '' (одинарные кавычки), результат будет ровно тот же, но читаться будет проще. 
Конкретно это условие будет выглядеть как 
```go 
if str[i] >= '0' && str[i] <= '9' || str[i] == '.' {
```

ну и остальные подобным образом

2021-11-25 20:54 UTC, v-lozhkin commented on homework3/main.go
> +		} else if str[i] == 45 {
switch без предиката здесь отлично подойдет вместо цепочки if-else

2021-11-25 20:54 UTC, v-lozhkin commented on homework3/main.go
> +		a, operation, b = calcArgumentsFromString(scannedString)
Крутая идея с парсером !

2021-11-29 13:23 UTC, amosipenko commented on homework3/main.go
> +		if str[i] >= 48 && str[i] <= 57 || str[i] == 46 {
fixed

2021-11-29 13:24 UTC, amosipenko commented on homework3/main.go
> +		} else if str[i] == 45 {
fixed
но в чем разность, только что меньше скобок?

2021-11-29 14:14 UTC, v-lozhkin commented on homework3/main.go
> +		} else if str[i] == 45 {
да. свитч всегда проще читать

2021-11-29 14:15 UTC, v-lozhkin approved these changes
Принято

2021-11-29 14:26 UTC, merged